# -*- coding: utf-8 -*-
"""
生成全国「市 -> 区/县」映射，写入前端 utils/city-districts.js，
并改写 utils/city.js 改为从 city-districts.js 导入并重导出（picker 无需改动）。

数据源：china-division pca-code.json（现行行政区划）。
直辖市（北京/天津/上海/重庆）的区挂在「市辖区」节点下；
普通省份直接列市，市下挂区/县/县级市。
直筒子市（东莞/中山/嘉峪关等）下一级是镇/街道，无区/县 -> 空数组，
由 picker 兜底「选整个市」。
"""
import json
import urllib.request
import os

BASE = r"D:\Users\35156\Documents\HBuilderProjects\quiz-miniapp"
DISTRICTS_FILE = os.path.join(BASE, "utils", "city-districts.js")
CITYJS_FILE = os.path.join(BASE, "utils", "city.js")

DATA_URL = "https://unpkg.com/china-division@latest/dist/pca-code.json"
MUNICIPALITIES = {"北京市", "天津市", "上海市", "重庆市"}


def fetch_data():
    req = urllib.request.Request(DATA_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def _clean(dists):
    # 只保留区/县/县级市/林区，排除「市辖区」聚合节点与镇/街道/乡
    out = [d for d in dists if d and d != "市辖区" and d.endswith(("区", "县", "市", "林"))]
    seen = set()
    uniq = []
    for d in out:
        if d not in seen:
            seen.add(d)
            uniq.append(d)
    return uniq


def build_map(data):
    result = {}
    collisions = []
    for prov in data:
        pname = prov.get("name")
        if pname in MUNICIPALITIES:
            # 直辖市：市辖区 / 县 节点的 grandchildren 才是真正的区/县
            dists = []
            for child in prov.get("children", []):
                for a in child.get("children", []):
                    nm = a.get("name")
                    if nm:
                        dists.append(nm)
            uniq = _clean(dists)
            if pname in result:
                collisions.append(pname)
                continue
            result[pname] = uniq
        else:
            # 普通省份：children 是市，市的 children 是区/县
            for city in prov.get("children", []):
                cname = city.get("name")
                if cname == "省直辖县级行政区划":
                    # 省直辖县级行政区划：直接管辖若干县/县级市，没有"市"这一层。
                    # 把它们各自作为可选项（无下属区，由 picker 兜底「选整个市」）。
                    for a in city.get("children", []):
                        nm = a.get("name")
                        if not nm:
                            continue
                        if nm in result:
                            collisions.append(nm)
                            continue
                        result[nm] = []
                    continue
                key = cname
                dists = [a.get("name") for a in city.get("children", []) if a.get("name")]
                uniq = _clean(dists)
                if key in result:
                    collisions.append(key)
                    continue
                result[key] = uniq
    return result, collisions


def write_districts(result):
    lines = []
    for city, dists in result.items():
        arr = "[" + ",".join('"%s"' % d for d in dists) + "]"
        lines.append('  "%s": %s,' % (city, arr))
    body = "\n".join(lines)
    header = (
        "// AUTO-GENERATED by tools/gen_city_districts.py — 不要手改，改脚本重跑。\n"
        "// 数据源：china-division (pca-code.json，现行行政区划)。\n"
        "// 结构：市名(全称) -> 下属区/县/县级市 数组。\n"
        "// 直筒子市(东莞/中山/嘉峪关/儋州等)无下辖区 -> 空数组，由 picker 兜底「选整个市」。\n"
        "export const CITY_DISTRICTS = {\n"
    )
    footer = "\n}\n"
    with open(DISTRICTS_FILE, "w", encoding="utf-8") as f:
        f.write(header + body + footer)


CITYJS = '''/**
 * 城市选择 / 缓存 / 定位
 * ------------------------------------------------------------
 * 为什么不直接 uni.getStorageSync('quiz_city')？
 *   键名集中在 config/storage.js 登记，这里做一层薄封装，
 *   将来键名改了、或者要换成"定位获取"，只改这个文件。
 *
 * 为什么不给默认城市，而是让用户自己选 / 主动定位？
 *   1. wx.getLocation 要弹系统授权框，个人主体小程序还要写隐私协议，
 *      首次进入就弹权限 = 劝退，所以不自动弹，只在用户点「定位」时才请求；
 *   2. 猜一个城市（比如默认成都）读出来的天气跟用户无关，属于假数据。
 *   所以首次进入展示"选城市"引导，选完 / 定位成功才真正发请求。
 *   定位走 locateCoord()，后端按经纬度反查到区/县，精度到区。
 */
import { STORAGE_KEYS } from '@/config/storage.js'

/**
 * 城市 -> 下属行政区（区 / 县 / 县级市）映射。
 * 数据为「全国市+区」静态快照（数据源 china-division，现行行政区划），
 * 由 tools/gen_city_districts.py 生成到 ./city-districts.js。
 * 地址选择组件据此做「市 -> 区」两级展示，粒度到区，符合日常使用习惯。
 *
 * 天气后端按 "城市+区"（如「成都武侯区」）去 GeoAPI 反查，与这里数据同源，
 * 所以选出来的区一定能查到天气。某行政区更名以官方为准；
 * 想增删城市/区，改 gen_city_districts.py 重跑，别手改 city-districts.js。
 */
export { CITY_DISTRICTS } from './city-districts.js'

/** 支持的城市列表（由上面映射推导，保持单一数据源） */
export const HOT_CITIES = Object.keys(CITY_DISTRICTS)

/** 读当前城市；没选过返回空串（而不是硬塞一个默认值） */
export function getCity() {
  return uni.getStorageSync(STORAGE_KEYS.CITY) || ''
}

export function setCity(city) {
  uni.setStorageSync(STORAGE_KEYS.CITY, city || '')
}

/**
 * 定位获取当前经纬度，拼成 "经度,纬度" 交给后端反查到区。
 * 后端 WeatherService 识别坐标串后走 GeoAPI 反查最近区/县，天气精度到区。
 * 用户主动点「定位」才弹授权，不自动弹（避免个人主体小程序一进就讨权限、劝退）。
 * (c) 微信侧前提：小程序后台已配置「地理位置」隐私声明，且 app.json 的
 *    requiredPrivateInfos 含 getLocation，否则 uni.getLocation 会直接 fail。
 * 失败抛错（权限拒绝 / 当前端不支持），由调用方降级到手动选城市。
 */
export function locateCoord() {
  return new Promise((resolve, reject) => {
    uni.getLocation({
      type: 'gcj02',
      success: (r) => resolve(`${r.longitude},${r.latitude}`),
      fail: (e) => reject(e)
    })
  })
}
'''


def main():
    data = fetch_data()
    result, collisions = build_map(data)
    write_districts(result)
    with open(CITYJS_FILE, "w", encoding="utf-8") as f:
        f.write(CITYJS)
    nodistrict = [c for c, d in result.items() if not d]
    print("CITIES:", len(result))
    print("AREAS:", sum(len(d) for d in result.values()))
    print("NO_DISTRICT_CITIES:", len(nodistrict))
    for c in nodistrict:
        print("  NODIST:", c)
    if collisions:
        print("COLLISIONS:", collisions)
    print("WROTE:", DISTRICTS_FILE)
    print("WROTE:", CITYJS_FILE)


if __name__ == "__main__":
    main()
